# -*- coding: utf-8 -*-
"""SpineSurgeryList_apply.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12n0RVSiehMKPmPurhqi9_r2GaitPxiTW
"""

# 한글 폰트 설치
!apt-get install -y fonts-nanum
!fc-cache -fv
!rm ~/.cache/matplotlib -rf
# 설치 후 colab 경우 Reuntime > Restart session 필요

import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.rc('font', family='NanumBarunGothic') # 혹은 다른 설치한 Nanum 폰트 사용

import pandas as pd

df_SSL = pd.read_csv('/content/SpineSurgeryList.csv')
df_SSL

"""## apply() 적용 BMI 컬럼 생성"""

df_SSL[["신장", "체중"]]

def BMI(params):
  df_BMI = round((params.loc['체중']/(params.loc['신장']*0.01)**2), 2)
  return df_BMI

df_SSL['BMI'] = df_SSL[["신장", "체중"]].apply(BMI, axis=1)

df_SSL

"""## optional] 수술시간(총 분) -> 시분 표시한 컬럼 생성"""

df_SSL['수술시간']

def operating_time(params):
  try :
    hour = int(params//60)
    min = int(params%60)
    if hour == 0:
      result = f"{min}분"
    else:
      result = f"{hour}시간 {min}분"
  except :
    result = "None"
  return result

df_SSL['수술시간_new'] = df_SSL['수술시간'].apply(operating_time)

df_SSL['수술시간_new']

